const types = {
  GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",

  GET_TOP_PRODUCTS: "GET_TOP_PRODUCTS",
  GET_NEW_PRODUCTS: "GET_NEW_PRODUCTS",
  GET_FEATURED_PRODUCTS: "GET_FEATURED_PRODUCTS",
  GET_SALE_PRODUCTS: "GET_SALE_PRODUCTS",

  REMOVE_PRODUCT: "REMOVE_PRODUCT",
  ADD_PRODUCT: "ADD_PRODUCT",
  INCREASE_COUNT: "INCREASE_COUNT",
  DECREASE_COUNT: "DECREASE_COUNT",
  CLEAR: "CLEAR",
  FETCH_PRODUCTS: "FETCH_PRODUCTS"
};

export default types;
