name: Run Lint

on:
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 16

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies for Client
        working-directory: client
        run: npm ci

      - name: Code Linting for Client
        working-directory: client
        run: npm run lint -- --ext .js,.jsx,.json --report-unused-disable-directives --max-warnings 0 --fix
