name: Run Lint

on:
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 16

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Dependencies
        run: cd ../../client && npm install
      - name: Code Linting
        run: cd ../../client && npm run lint
