name: Run Lint

on:
  pull_request:
    branches:
      - main

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Code Linting for Client
        working-directory: client
        run: npx eslint src --ext .js,.jsx,.json --report-unused-disable-directives --max-warnings 0 --fix
